# Numpy(Numerical Python)

## 核心数据结构ndarray
![ndarray](pic/numpy_and_pandas/ndarray.jpg)

In [2]:
!pip install numpy
import numpy as np

Looking in indexes: https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple


## 一维数组
![](./pic/numpy_and_pandas/one_dim.jpg)

In [3]:
arr = np.array([5, 17, 3, 26, 31])
print(arr)
type(arr)

[ 5 17  3 26 31]


numpy.ndarray

![](./pic/numpy_and_pandas/search_items.jpg)

In [4]:
print(arr[0])
print(arr[0:3])
for element in arr:
    print(element)

5
[ 5 17  3]
5
17
3
26
31


## numpy数组中的数据类型要保持一致
![](./pic/numpy_and_pandas/datatype.jpg)

In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
# 返回数组维度数
print(arr.ndim)
print(arr2.ndim)

1
2


In [7]:
# 返回数组维度
print(arr.shape)
print(arr2.shape)

(5,)
(2, 3)


In [8]:
# 返回数组类型
print(arr.dtype)
print(arr2.dtype)

int64
int64


In [9]:
# 创建一个全0数组
zeros_arr = np.zeros([2, 3])
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# 创建一个全1数组
ones_arr = np.ones([2, 3])
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# 返回一个范围数组
arange_arr = np.arange(0,   10,    2)
                    #  起始  终止   步长
print(arange_arr)

[0 2 4 6 8]


In [12]:
# 拼接数组
con_arr = np.concatenate([arr, np.zeros([2,])])
print(con_arr)

[ 5. 17.  3. 26. 31.  0.  0.]


In [13]:
# 数组排序
## 副本排序
con_arr_sorted = np.sort(con_arr)
print(f"{con_arr_sorted=}") # 开辟一块新的内存空间，进行排序，返回新的数组
print(f"{con_arr=}")        # 本身没有被排序

## 原地排序     
con_arr.sort()          # 原地排序，不开辟新的内存空间
print(f"{con_arr=}")

con_arr_sorted=array([ 0.,  0.,  3.,  5., 17., 26., 31.])
con_arr=array([ 5., 17.,  3., 26., 31.,  0.,  0.])
con_arr=array([ 0.,  0.,  3.,  5., 17., 26., 31.])


![](./pic/numpy_and_pandas/ndarray_index.jpg)

In [14]:
# 索引和切片
arr1 = np.array([3, 5, 17, 26, 31])
print(arr1)

## 索引
print(arr1[0])
print(arr1[-2])

## 切片
print(arr1[1:4])

[ 3  5 17 26 31]
3
26
[ 5 17 26]


![](./pic/numpy_and_pandas/ndarray_add.jpg)

In [15]:
arr4 = np.array([6, 7, 8, 9, 10])
arr5 = np.array([1, 1, 1, 1, 1])
print(arr4 + arr5)

[ 7  8  9 10 11]


In [16]:
print(arr4 * arr5)      # 哈达玛积 hadamard product

[ 6  7  8  9 10]


In [17]:
print(arr4 * 3)      # 广播

[18 21 24 27 30]


In [ ]:
print(arr4.max())   # 最大值
print(arr4.min())   # 最小值
print(arr4.sum())   # 求和
print(arr4.mean())  # 求平均


10
6
40
8.0


In [20]:
# 找到所有大于6的数字
print(arr4>6)
print(arr4[arr4>6])

[False  True  True  True  True]
[ 7  8  9 10]


In [22]:
print((arr4>6) & (arr4 < 9))
print(arr4[(arr4>6) & (arr4 < 9)])

[False  True  True False False]
[7 8]
